language: node_js
node_js:
  - stable
addons:
  apt:
    packages:
      - sshpass
  ssh_known_hosts:
    - $ADDRESS:$PORT
cache:
  apt: true
  directories:
    - node_modules
install:
  - cd ./server
  - npm install
  - npm run build
  - cd ../
script:
  - sshpass -p "$PASSWORD" rsync --progress -azvh --update --exclude='.git/' --filter=":- .gitignore" --exclude='.travis.yml' -e "ssh -p $PORT" "./" "$USERNAME@$ADDRESS:$PROJECT_FOLDER/"
after_script:
  - sshpass -p "$PASSWORD" ssh -t -p "$PORT" -oStrictHostKeyChecking=no "$USERNAME@$ADDRESS" "bash -s" < ./build.sh "$PROJECT_FOLDER" "$PROJECT_PORT"
