language: node_js
node_js:
  - stable
addons:
  apt:
    packages:
      - sshpass
  ssh_known_hosts:
    - $ADDRESS:$PORT
cache:
  apt: true
  directories:
    - node_modules
before_install:
  - cd ./server
install:
  - npm install
script:
  - npm run build
after_script:
  - cd ../
  - sshpass -p $PASSWORD rsync --progress -azvh --update -e ssh -p $PORT ./server/ $USERNAME@$ADDRESS:/home/mulavhe/www/JMRSquaredDev/server
  - sshpass -p $PASSWORD ssh -t -p $PORT $USERNAME@$ADDRESS "uname -a"
  - cat "./bash.sh" | sshpass -p "$PASSWORD" ssh -t -p "$PORT" -oStrictHostKeyChecking=no "$USERNAME@$ADDRESS"
deploy:
  provider: script
  skip_cleanup: true
  script: bash "./deploy.sh" $PASSWORD $PORT $USERNAME $ADDRESS "/home/mulavhe/www/JMRSquaredDev"
  on:
    branch: develop
