language: node_js
node_js:
  - stable
addons:
  apt:
    packages:
      - sshpass
  ssh_known_hosts:
    - server.jmrsquared.com:7822
    - 68.66.193.181:7822
cache:
  apt: true
  directories:
    - node_modules
before_install:
  - cd ./server
install:
  - npm install
  - npm run build
before_deploy:
  - cd ../
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ".travis/deploy.sh" $USERNAME $PASSWORD $ADDRESS $PORT ./bash.sh
    on:
      branch: develop
