language: node_js
node_js:
  - stable
addons:
  apt:
    packages:
      - sshpass
  ssh_known_hosts:
    - $ADDRESS:$PORT
cache:
  apt: true
  directories:
    - node_modules
install:
  - cd ./server
  - npm install
  - npm run build
  - cd ../
script:
  - sshpass -p $PASSWORD rsync --progress -azvh --update -e "ssh -p $PORT" "./*" "$USERNAME@$ADDRESS:/home/mulavhe/www/JMRSquaredDev/"
# deploy:
#   provider: script
#   skip_cleanup: true
#   script: sshpass -p $PASSWORD rsync --progress -azvh --update -e ssh -p "$PORT" "./*" "$USERNAME@$ADDRESS:/home/mulavhe/www/JMRSquaredDev/"
#   on:
#     branch: develop
after_script:
  - cat "./bash.sh /home/mulavhe/www/JMRSquaredDev 3000" | sshpass -p "$PASSWORD" ssh -t -p "$PORT" -oStrictHostKeyChecking=no "$USERNAME@$ADDRESS"
