language: node_js
node_js:
  - stable
addons:
  apt:
    packages:
      - sshpass
  ssh_known_hosts:
    - server.jmrsquared.com:7822
    - 68.66.193.181:7822
cache:
  apt: true
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_1c10fd10ce13_key -iv $encrypted_1c10fd10ce13_iv
    -in .travis/deploy_jmrsquared_rsa.enc -out .travis/deploy_jmrsquared_rsa -d
  - eval "$(ssh-agent -s)"
  - cp .travis/deploy_jmrsquared_rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa
  - cd ./server
install:
  - npm install
  - npm run build
before_deploy:
  - cd ../
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ".travis/deploy.sh" $USERNAME $PASSWORD $ADDRESS $PORT
    on:
      branch: develop
